version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /node_modules
      - .:/src
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /node_modules
      - .:/src
    command: ["npm", "run", "test"]